-- MySQL Script generated by MySQL Workbench
-- lun 19 nov 2018 01:26:32 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WrongWord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WrongWord` (
  `id` INT NOT NULL,
  `label` LONGTEXT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_WrongWord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_WrongWord` (
  `User_id` INT NOT NULL,
  `WrongWord_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`User_id`, `WrongWord_id`),
  INDEX `fk_User_has_WrongWord_WrongWord1_idx` (`WrongWord_id` ASC),
  INDEX `fk_User_has_WrongWord_User_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_WrongWord_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_WrongWord_WrongWord1`
    FOREIGN KEY (`WrongWord_id`)
    REFERENCES `mydb`.`WrongWord` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
